name: deploy
on:
  workflow_dispatch:

jobs:
  app-setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci
        shell: bash

      - name: Build app
        run: npm run build

      - name: Export app
        run: npm run export

      - name: Deploy
        if: ${{ failure() }}
        run: echo "Deploying app"
